apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: state-machine
  namespace: state-machine
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - smachine.juicyapi.com
      secretName: smachine-juicyapi-tls
  rules:
    - host: smachine.juicyapi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: state-machine
                port:
                  number: 80
